plugins {
    id 'java'
    id 'java-library'
    id 'idea'
    id 'antlr'
    id 'maven-publish'
    id "com.vanniktech.maven.publish"
}

group = 'com.xkball.xklib.ui'
version = '0.0.1'

repositories {
    mavenCentral()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    api "dev.vfyjxf:taffy:1.1.4"
    api 'org.antlr:antlr4-runtime:4.13.2'
    antlr "org.antlr:antlr4:4.13.2"

    implementation project(":xklib-3d")
    runtimeOnly project(":xklib-3d-gl")

    annotationProcessor project(":xklib-ap")
    annotationProcessor "com.google.auto.service:auto-service:1.1.1"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Automatic-Module-Name': 'com.xkball.xklib.ui'
        )
    }
}

generateGrammarSource {
    arguments += ['-package', 'com.xkball.xklib.antlr.css']
    outputDirectory = outputDirectory.toPath().resolve("com/xkball/xklib/antlr/css").toFile()
}

mavenPublishing {
    publishToMavenCentral(true)
    signAllPublications()
    coordinates("com.xkball", "xklib-ui", version)

    pom {
        name = "xklib-ui"
        url = "https://github.com/xkball/xklib-ui"
        description = "a minecraft mod lib."

        licenses {
            license {
                name = 'GNU LESSER GENERAL PUBLIC LICENSE Version 3 '
                url = 'https://www.gnu.org/licenses/lgpl-3.0.html'
            }
        }

        developers {
            developer {
                id = 'xkball'
                name = 'xkball'
                email = 'xkball996@gmail.com'
            }
        }

        scm {
            connection = 'scm:git:git://github.com/xkball/xklib-ui.git'
            developerConnection = 'scm:git:ssh://github.com/xkball/xklib-ui.git'
            url = 'https://github.com/xkball/xklib-ui/tree/master'
        }
    }
}